pub mod auth;
pub mod downloads;
pub mod grab;
pub mod help;
pub mod library;
pub mod notifications;
pub mod oauth;
pub mod progress;
pub mod responses;
pub mod search;
pub mod settings;
pub mod system;

pub mod arr_auth;
pub mod arr_shared;
pub mod media;
pub mod radarr_compat;
pub mod sonarr_compat;
pub mod webhook;
